### ISSUE TITLE
strtok() C implementation

### ISSUE THREAD

**Issue by lachesis** [antonmks/nvParse#4]
Can you upload your CPU implementation?

**Comment by antonmks** [comment]
Here's a faster, multithreaded CPU implementation : https://gist.github.com/nguillemot/75f7bb30b45811451422
It runs in 1.6 seconds on my PC.

**Comment by lachesis** [comment]
Here's a C implementation that I just whipped up from the strtok_r manpage example and mmap. It's single-threaded and runs in about 2.3 seconds on my PC.

https://gist.github.com/lachesis/39cf67044f651ae24bcc

Interestingly, cut runs even faster! 1.442 seconds! What made cut run so slowly for you? If the time is bounded by disk IO, you wouldn't expect it to be any faster for the GPU implementation, unless you had just warmed up your disk cache.

```
$ time cut -d "|" -f 6 lineitem.tbl > /dev/null
cut -d "|" -f 6 lineitem.tbl > /dev/null  1.35s user 0.09s system 99% cpu 1.442 total
```

**Comment by antonmks** [comment]
I'm not sure why cut takes so long, it  still takes 28 seconds on my PC.
Your program runs in 3.9 seconds on my machine if I remove printfs. Which sounds about right if you consider that the original strtok program run the conversions to binary values for every column and stored  every resulting column in a separate array.
My GPU program runs now in 0.4 seconds (excluding CUDA initialization), so it is still might be worth to use GPU in some cases..

**Comment by guohaoding** [comment]
> Here's a faster, multithreaded CPU implementation : https://gist.github.com/nguillemot/75f7bb30b45811451422
> It runs in 1.6 seconds on my PC.

This link has expired, can you update it?

**Comment by antonmks** [comment]
> 
> 
> > Here's a faster, multithreaded CPU implementation : https://gist.github.com/nguillemot/75f7bb30b45811451422
> > It runs in 1.6 seconds on my PC.
> 
> This link has expired, can you update it?

Sorry, I don't have it, it is not my gist.
